#!/usr/bin/python

"""
Custom topology for Mininet - Airtel network.
Generated by GraphML-Topo-to-Mininet-Network-Generator.
"""

from mininet.topo import Topo


class GeneratedTopo(Topo):
    """Internet Topology Zoo Specimen - Airtel Network."""

    def __init__(self, **opts):
        """Create the Airtel network topology."""
        # Initialize Topology
        Topo.__init__(self, **opts)

        # Add switches
        LosAngeles = self.addSwitch("s0")
        Chennai = self.addSwitch("s1")
        NYIX = self.addSwitch("s2")
        LAIX = self.addSwitch("s3")
        NiXI = self.addSwitch("s4")
        LINX = self.addSwitch("s5")
        EQUINOXIX = self.addSwitch("s6")
        NewYork = self.addSwitch("s7")
        London = self.addSwitch("s8")
        Mumbai = self.addSwitch("s9")
        Palermo = self.addSwitch("s10")
        Marseille = self.addSwitch("s11")
        HKIX = self.addSwitch("s12")
        HongKong = self.addSwitch("s13")
        Singapore = self.addSwitch("s14")
        STIX = self.addSwitch("s15")

        # Add hosts
        LosAngeles_host = self.addHost("h0")
        Chennai_host = self.addHost("h1")
        NYIX_host = self.addHost("h2")
        LAIX_host = self.addHost("h3")
        NiXI_host = self.addHost("h4")
        LINX_host = self.addHost("h5")
        EQUINOXIX_host = self.addHost("h6")
        NewYork_host = self.addHost("h7")
        London_host = self.addHost("h8")
        Mumbai_host = self.addHost("h9")
        Palermo_host = self.addHost("h10")
        Marseille_host = self.addHost("h11")
        HKIX_host = self.addHost("h12")
        HongKong_host = self.addHost("h13")
        Singapore_host = self.addHost("h14")
        STIX_host = self.addHost("h15")

        # Add edges between switch and corresponding host
        self.addLink(LosAngeles, LosAngeles_host)
        self.addLink(Chennai, Chennai_host)
        self.addLink(NYIX, NYIX_host)
        self.addLink(LAIX, LAIX_host)
        self.addLink(NiXI, NiXI_host)
        self.addLink(LINX, LINX_host)
        self.addLink(EQUINOXIX, EQUINOXIX_host)
        self.addLink(NewYork, NewYork_host)
        self.addLink(London, London_host)
        self.addLink(Mumbai, Mumbai_host)
        self.addLink(Palermo, Palermo_host)
        self.addLink(Marseille, Marseille_host)
        self.addLink(HKIX, HKIX_host)
        self.addLink(HongKong, HongKong_host)
        self.addLink(Singapore, Singapore_host)
        self.addLink(STIX, STIX_host)

        # Add edges between switches
        self.addLink(LosAngeles, Chennai, bw=10, delay="73.27482825340296ms")
        self.addLink(LosAngeles, Chennai, bw=10, delay="73.27482825340296ms")
        self.addLink(LosAngeles, LAIX, bw=10, delay="73.27482825340296ms")
        self.addLink(LosAngeles, HongKong, bw=10, delay="59.21827359707304ms")
        self.addLink(LosAngeles, Singapore, bw=10, delay="71.77384479147044ms")
        self.addLink(LosAngeles, Singapore, bw=10, delay="71.77384479147044ms")
        self.addLink(LosAngeles, NewYork, bw=10, delay="20.000731794474888ms")
        self.addLink(LosAngeles, NewYork, bw=10, delay="20.000731794474888ms")
        self.addLink(LosAngeles, NewYork, bw=10, delay="20.000731794474888ms")
        self.addLink(Chennai, NewYork, bw=10, delay="68.46530014418029ms")
        self.addLink(Chennai, NewYork, bw=10, delay="68.46530014418029ms")
        self.addLink(Chennai, NewYork, bw=10, delay="68.46530014418029ms")
        self.addLink(Chennai, London, bw=10, delay="41.72590241795402ms")
        self.addLink(Chennai, Mumbai, bw=10, delay="5.24191404447388ms")
        self.addLink(Chennai, Palermo, bw=10, delay="36.098715854487054ms")
        self.addLink(Chennai, Marseille, bw=10, delay="39.61713706085268ms")
        self.addLink(Chennai, HongKong, bw=10, delay="18.916211824565593ms")
        self.addLink(Chennai, Singapore, bw=10, delay="14.778167816925682ms")
        self.addLink(Chennai, Singapore, bw=10, delay="14.778167816925682ms")
        self.addLink(NYIX, NewYork, bw=10, delay="68.46530014418029ms")
        self.addLink(NiXI, Mumbai, bw=10, delay="5.24191404447388ms")
        self.addLink(LINX, London, bw=10, delay="41.72590241795402ms")
        self.addLink(EQUINOXIX, Singapore, bw=10, delay="14.778167816925682ms")
        self.addLink(NewYork, London, bw=10, delay="28.306870885798496ms")
        self.addLink(NewYork, London, bw=10, delay="28.306870885798496ms")
        self.addLink(NewYork, London, bw=10, delay="28.306870885798496ms")
        self.addLink(NewYork, Mumbai, bw=10, delay="63.739302770462416ms")
        self.addLink(NewYork, Mumbai, bw=10, delay="63.739302770462416ms")
        self.addLink(NewYork, Marseille, bw=10, delay="32.04956524814997ms")
        self.addLink(NewYork, Singapore, bw=10, delay="77.95227123050866ms")
        self.addLink(London, Mumbai, bw=10, delay="36.56198448572607ms")
        self.addLink(London, Mumbai, bw=10, delay="36.56198448572607ms")
        self.addLink(London, Marseille, bw=10, delay="5.0935748660588205ms")
        self.addLink(London, Singapore, bw=10, delay="55.16443977700803ms")
        self.addLink(HKIX, HongKong, bw=10, delay="49.446807471527315ms")
        self.addLink(HongKong, Singapore, bw=10, delay="13.147333590355496ms")
        self.addLink(Singapore, STIX, bw=10, delay="4.824449114388016e-07ms")


topos = {"generated": (lambda: GeneratedTopo())}
