#!/usr/bin/python

"""
Custom topology for Mininet, generated by GraphML-Topo-to-Mininet-Network-Generator.
"""

from mininet.cli import CLI
from mininet.link import TCLink
from mininet.log import setLogLevel
from mininet.net import Mininet
from mininet.node import CPULimitedHost, Node, RemoteController
from mininet.topo import Topo
from mininet.util import dumpNodeConnections


class GeneratedTopo(Topo):
    "Internet Topology Zoo Specimen."

    def __init__(self, **opts):
        "Create a topology."

        # Initialize Topology
        Topo.__init__(self, **opts)

        # add nodes, switches first...
        Djelfa = self.addSwitch("s0")
        Medea = self.addSwitch("s1")
        Internet = self.addSwitch("s2")
        Blida = self.addSwitch("s3")
        ElOued = self.addSwitch("s4")
        Msila = self.addSwitch("s5")
        Laghouat = self.addSwitch("s6")
        Ouargla = self.addSwitch("s7")
        Constantine = self.addSwitch("s8")
        Biskra = self.addSwitch("s9")
        Batna = self.addSwitch("s10")
        TiziOuzou = self.addSwitch("s11")
        Annaba = self.addSwitch("s12")
        Guelma = self.addSwitch("s13")
        Tebessa = self.addSwitch("s14")
        OumelBouaghi = self.addSwitch("s15")
        Bejaia = self.addSwitch("s16")
        Setif = self.addSwitch("s17")
        Skikda = self.addSwitch("s18")
        Jijel = self.addSwitch("s19")
        Tiaret = self.addSwitch("s20")
        GEANT = self.addSwitch("s21")
        Alger = self.addSwitch("s22")
        Chlef = self.addSwitch("s23")
        Oran = self.addSwitch("s24")
        Mostaganem = self.addSwitch("s25")
        Tlemcen = self.addSwitch("s26")
        SidiBelAbbes = self.addSwitch("s27")
        Saida = self.addSwitch("s28")
        Mascara = self.addSwitch("s29")

        # ... and now hosts
        Djelfa_host = self.addHost("h0")
        Medea_host = self.addHost("h1")
        Internet_host = self.addHost("h2")
        Blida_host = self.addHost("h3")
        ElOued_host = self.addHost("h4")
        Msila_host = self.addHost("h5")
        Laghouat_host = self.addHost("h6")
        Ouargla_host = self.addHost("h7")
        Constantine_host = self.addHost("h8")
        Biskra_host = self.addHost("h9")
        Batna_host = self.addHost("h10")
        TiziOuzou_host = self.addHost("h11")
        Annaba_host = self.addHost("h12")
        Guelma_host = self.addHost("h13")
        Tebessa_host = self.addHost("h14")
        OumelBouaghi_host = self.addHost("h15")
        Bejaia_host = self.addHost("h16")
        Setif_host = self.addHost("h17")
        Skikda_host = self.addHost("h18")
        Jijel_host = self.addHost("h19")
        Tiaret_host = self.addHost("h20")
        GEANT_host = self.addHost("h21")
        Alger_host = self.addHost("h22")
        Chlef_host = self.addHost("h23")
        Oran_host = self.addHost("h24")
        Mostaganem_host = self.addHost("h25")
        Tlemcen_host = self.addHost("h26")
        SidiBelAbbes_host = self.addHost("h27")
        Saida_host = self.addHost("h28")
        Mascara_host = self.addHost("h29")

        # add edges between switch and corresponding host
        self.addLink(Djelfa, Djelfa_host)
        self.addLink(Medea, Medea_host)
        self.addLink(Internet, Internet_host)
        self.addLink(Blida, Blida_host)
        self.addLink(ElOued, ElOued_host)
        self.addLink(Msila, Msila_host)
        self.addLink(Laghouat, Laghouat_host)
        self.addLink(Ouargla, Ouargla_host)
        self.addLink(Constantine, Constantine_host)
        self.addLink(Biskra, Biskra_host)
        self.addLink(Batna, Batna_host)
        self.addLink(TiziOuzou, TiziOuzou_host)
        self.addLink(Annaba, Annaba_host)
        self.addLink(Guelma, Guelma_host)
        self.addLink(Tebessa, Tebessa_host)
        self.addLink(OumelBouaghi, OumelBouaghi_host)
        self.addLink(Bejaia, Bejaia_host)
        self.addLink(Setif, Setif_host)
        self.addLink(Skikda, Skikda_host)
        self.addLink(Jijel, Jijel_host)
        self.addLink(Tiaret, Tiaret_host)
        self.addLink(GEANT, GEANT_host)
        self.addLink(Alger, Alger_host)
        self.addLink(Chlef, Chlef_host)
        self.addLink(Oran, Oran_host)
        self.addLink(Mostaganem, Mostaganem_host)
        self.addLink(Tlemcen, Tlemcen_host)
        self.addLink(SidiBelAbbes, SidiBelAbbes_host)
        self.addLink(Saida, Saida_host)
        self.addLink(Mascara, Mascara_host)

        # add edges between switches
        self.addLink(Djelfa, Alger, bw=10, delay="1.1795553962196086ms")
        self.addLink(Medea, Alger, bw=10, delay="0.30538337812128297ms")
        self.addLink(Internet, Alger, bw=10, delay="0.30538337812128297ms")
        self.addLink(Blida, Alger, bw=10, delay="0.18687249245089305ms")
        self.addLink(ElOued, Ouargla, bw=10, delay="1.0804537903807705ms")
        self.addLink(Msila, Constantine, bw=10, delay="0.4593999964133801ms")
        self.addLink(Laghouat, Ouargla, bw=10, delay="1.5672166647245824ms")
        self.addLink(Ouargla, Alger, bw=10, delay="2.9153722531427086ms")
        self.addLink(Constantine, Biskra, bw=10, delay="0.9478534771000013ms")
        self.addLink(Constantine, Batna, bw=10, delay="0.49960245825299376ms")
        self.addLink(Constantine, Annaba, bw=10, delay="0.6035300175696876ms")
        self.addLink(Constantine, Guelma, bw=10, delay="0.3730213258137001ms")
        self.addLink(Constantine, Tebessa, bw=10, delay="0.8788110158688025ms")
        self.addLink(Constantine, OumelBouaghi, bw=10, delay="0.3582975623305138ms")
        self.addLink(Constantine, Skikda, bw=10, delay="0.3182318176232132ms")
        self.addLink(Constantine, Jijel, bw=10, delay="0.4629080421491639ms")
        self.addLink(Constantine, Alger, bw=10, delay="1.6362633874912575ms")
        self.addLink(TiziOuzou, Alger, bw=10, delay="0.4552355460501672ms")
        self.addLink(Bejaia, Alger, bw=10, delay="0.9246479004541402ms")
        self.addLink(Setif, Alger, bw=10, delay="1.123415054566417ms")
        self.addLink(Tiaret, Oran, bw=10, delay="0.9186668603688821ms")
        self.addLink(GEANT, Alger, bw=10, delay="1.109134369347179ms")
        self.addLink(Alger, Chlef, bw=10, delay="0.8705851971284001ms")
        self.addLink(Alger, Oran, bw=10, delay="1.7829808420384452ms")
        self.addLink(Oran, Mostaganem, bw=10, delay="0.3613331986659133ms")
        self.addLink(Oran, Tlemcen, bw=10, delay="0.55443324887606ms")
        self.addLink(Oran, SidiBelAbbes, bw=10, delay="0.28324171918876423ms")
        self.addLink(Oran, Saida, bw=10, delay="0.6087538073453341ms")
        self.addLink(Oran, Mascara, bw=10, delay="0.3452850173313989ms")


topos = {"generated": (lambda: GeneratedTopo())}

# HERE THE CODE DEFINITION OF THE TOPOLOGY ENDS

# the following code produces an executable script working with a remote controller
# and providing ssh access to the the mininet hosts from within the ubuntu vm
controller_ip = ""


def setupNetwork(controller_ip):
    "Create network and run simple performance test"
    # check if remote controller's ip was set
    # else set it to localhost
    topo = GeneratedTopo()
    if controller_ip == "":
        # controller_ip = '10.0.2.2';
        controller_ip = "127.0.0.1"
    net = Mininet(
        topo=topo,
        controller=lambda a: RemoteController(a, ip=controller_ip, port=6633),
        host=CPULimitedHost,
        link=TCLink,
    )
    return net


def connectToRootNS(network, switch, ip, prefixLen, routes):
    "Connect hosts to root namespace via switch. Starts network."
    "network: Mininet() network object"
    "switch: switch to connect to root namespace"
    "ip: IP address for root namespace node"
    "prefixLen: IP address prefix length (e.g. 8, 16, 24)"
    "routes: host networks to route to"
    # Create a node in root namespace and link to switch 0
    root = Node("root", inNamespace=False)
    intf = TCLink(root, switch).intf1
    root.setIP(ip, prefixLen, intf)
    # Start network that now includes link to root namespace
    network.start()
    # Add routes from root ns to hosts
    for route in routes:
        root.cmd("route add -net " + route + " dev " + str(intf))


def sshd(network, cmd="/usr/sbin/sshd", opts="-D"):
    "Start a network, connect it to root ns, and run sshd on all hosts."
    switch = network.switches[0]  # switch to use
    ip = "10.123.123.1"  # our IP address on host network
    routes = ["10.0.0.0/8"]  # host networks to route to
    connectToRootNS(network, switch, ip, 8, routes)
    for host in network.hosts:
        host.cmd(cmd + " " + opts + "&")

    # DEBUGGING INFO
    print()
    print("Dumping host connections")
    dumpNodeConnections(network.hosts)
    print()
    print("*** Hosts are running sshd at the following addresses:")
    print()
    for host in network.hosts:
        print(host.name, host.IP())
    print()
    print("*** Type 'exit' or control-D to shut down network")
    print()
    print(
        "*** For testing network connectivity among the hosts, wait a bit for the controller to create all the routes, then do 'pingall' on the mininet console."
    )
    print()

    CLI(network)
    for host in network.hosts:
        host.cmd("kill %" + cmd)
    network.stop()


if __name__ == "__main__":
    setLogLevel("info")
    # setLogLevel('debug')
    sshd(setupNetwork(controller_ip))
